---
- hosts: all

#file: roles/common/tasks/updatepkg.yml
  tasks:
    - name: update source packages
      apt: update_cache=yes
      sudo: True

    - name: upgrade source packages
      apt: upgrade=dist
      sudo: True
