---
#file: roles/common/tasks/main.yml

- name: make sure file2ban is installed
  apt: pkg=fail2ban state=installed
  tags: fail2ban

- name: copy configuration file
  shell: cp /etc/fail2ban/jail.conf /etc/fail2ban/jail.local
