---
#file: roles/common/tasks/main.yml

- name: make sure file2ban is installed
  sudo: True
  apt: pkg=fail2ban state=installed
  tags: fail2ban

- name: copy configuration file
  sudo: True
  template: src=jail.local.j2 dest=/etc/fail2ban/jail.local
  notify:
    - restart fail2ban
  tags: fail2ban
